GLOSSARY = {"Email_Address": ["android.accounts.AccountManager.getAccounts",
                            "android.accounts.AccountManager.getAccountsByType",
                            "android.accounts.AccountManager.getAccountsByTypeAndFeatures",
                            "android.accounts.AccountManager.getAccountsByTypeForPackage",
                            "android.accounts.AccountManager.hasFeatures",
                            "android.net.MailTo.getTo",
                            "android.net.MailTo.getCc"],
            "Contact_Phone_Number":["android.telephony.TelephonyManager.getLine1Number"],
            "Identifier Cookie": ["android.webkit.CookieManager.getInstance"],
            "Identifier Device ID": ["android.provider.Settings.Secure.getString"],
            "Identifier IMEI": ["android.telephony.TelephonyManager.getDeviceId",
                                "android.telephony.TelephonyManager.getImei"],
            "Identifier IMSI": ["android.telephony.TelephonyManager.getSubscriberId"],
            "Identifier MAC": ["android.net.wifi.WifiInfo.getMacAddress"],
            "Identifier Mobile Carrier": ["android.telephony.TelephonyManager.getNetworkOperator",
                                          "android.telephony.TelephonyManager.getNetworkOperatorName",
                                            "android.telephony.TelephonyManager.getSimOperator",
                                            "android.telephony.TelephonyManager.getSimOperatorName"],
            "Identifier SIM Serial": ["android.telephony.TelephonyManager.getSimSerialNumber"],
            "Identifier SSID BSSID": ["android.net.wifi.WifiManager.getConfiguredNetworks",
                                        "android.net.wifi.WifiInfo.getBSSID",
                                        "android.net.wifi.WifiInfo.getSSID"],
            "Location Cell Tower": ["FusedLocationProviderClient.getLastLocation",
                                    "android.location.LocationManager.requestLocationUpdates",
                                    "android.location.LocationManager.requestSingleUpdate",
                                    "android.location.LocationManager.getLastKnownLocation",
                                    "android.location.LocationManager.addProximityAlert",
                                    "android.telephony.gsm.GsmCellLocation.getCid",
                                    "android.telephony.gsm.GsmCellLocation.getLac",
                                    "android.telephony.TelephonyManager.getCellLocation",
                                    "android.telephony.TelephonyManager.getAllCellInfo",
                                    "android.telephony.TelephonyManager.getNeighboringCellInfo"],
            "Location GPS and WiFi": ["FusedLocationProviderClient.getLastLocation",
                                        "android.location.LocationManager.requestLocationUpdates",
                                        "android.location.LocationManager.requestSingleUpdate",
                                        "android.location.LocationManager.getLastKnownLocation",
                                        "android.location.LocationManager.addProximityAlert"]}

